# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'hk-eform-ipad' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hk-eform-ipad

    pod 'MBProgressHUD', '~> 1.1.
end
